Ts verify
dyninst/testsuite pull request #167
Opened 2020-09-13 13:59 UTC by bigtrak

These changes ... do not change anything in the testsuite.  It is exactly the same, test-wise,
as it was before.

What they do is make the generation of the platform dirs to be completely automated,
and increase uniformity between the platforms ancillary files.  You can 'rm -rf' a platform
directory, and .. on a platform where gprolog works ... it will re-create it exactly.

Although tuples.gz has changed, 'tuples' itself is identical to the previous version, as are the generated
files.   Test results are identical to previous.  The build process has changed to make the compressed
tuples.gz files the same as the prior ... if changes did not occur to the test specification.

Makefile.genspec is reformatted to take better advantage of VCS facilities, to ensure changes are
easily spotted.

The deletions are files that are no longer generated or used by the testsuite.

I've also added some notes, so that someone else who has never created the platform from the specification, has some guidelines and hints of how to proceed.

2020-09-13 22:41 UTC, hainest requested changes

2020-09-13 22:41 UTC, hainest commented on Makefile.genspec
> +##	src/specification/spec-ungrouped.pl		-- no longer works
If that file doesn't work, let's just remove it.

2020-09-13 22:41 UTC, hainest commented on Makefile.genspec
> +## Recommended method to generate a new specification, is to:
"specification" here means a different variant on an existing test or a new platform?

2020-09-13 22:41 UTC, hainest commented on Makefile.genspec
> +##		make -f Makefile.gespec gen-clean gen-all
sp: Makefile.genspec

2020-09-13 22:41 UTC, hainest commented on Makefile.genspec
> +##	nB: You can make 1 platform by specifying it as a target;
Could you clarify this a bit?

2020-09-13 22:41 UTC, hainest commented on Makefile.genspec
> +## 4) Use both diff and git to compare the results.
What is being compared here? The generated CMakeLists.txt file?

2020-09-13 22:41 UTC, hainest commented on Makefile.genspec
> +##    and you need to find a platform which generates byte-for-byte identical
Gross. That prolog stuff has to go.

2020-09-13 22:41 UTC, hainest commented on Makefile.genspec
> +	arm64-unknown-linux		\
The only SUBDIRs (i.e., platforms) not deprecated are x86_64-unknown-linux2.4, ppc64_linux, aarch64-unknown-linux. All the others are dead- for testing purposes. We may someday get back around to testing on FreeBSD.

2020-09-13 22:41 UTC, hainest commented on Makefile.genspec
> +SPEC=spec-ungrouped.pl
Why the extra SPEC?

2020-09-13 22:41 UTC, hainest commented on Makefile.genspec
> +$(SUBDIRS:%=%/.gitignore): Makefile.genspec
Splitting these by platform is overkill. I would just make a "master" .gitignore and copy it into the new dirs.

2020-09-13 22:42 UTC, hainest commented
This is great! I just have a few items I don't fully understand; see the review comments.

2020-09-18 14:43 UTC, bigtrak commented
Tim, this PR is setup as a checkins/ pull request to 
make a "new baseline" of -exactly-as-before- performance and
reliability.  The files are the same, but now they are generated
by a repeatable mechanism.

Once this setup is in the mainline, in the future I could then make
some of the other changes you propose, which may change or remove
functionality or alter results of the testsuite.


I have addressed some of the issues you mention which follow that model
shortly, as well as correct spelling typo.

I've also reworded the notes, and adjusted them after determining
that the ubuntu-provided gprolog was the source of failure, not
gprolog itself.    gprolog works both pie and non-pie on those
systems, by the way, that wasn't the issue, just the ubuntu packaging.

I contacted Matt Legendre to ask about the status of spec-ungrouped.pl,
he thinks it can go the way of the dodo bird.   As that will not cause
changes in the test results, that has been taken care of as well.

I think the PR should still valid, as it should follow the branch head,
even after the additional commits.

Bolo

2020-09-20 23:07 UTC, hainest approved these changes

2020-09-20 23:08 UTC, hainest commented
LGTM. You can merge whenever you like.

2020-09-28 16:43 UTC, merged